import React, { useEffect, useState, useRef, useMemo } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import {
  StageSpinner,
  FireworkSpinner,
  MetroSpinner,
} from 'react-spinners-kit';
import TopBar from '../common/TopBar';
import Container from '../common/Container';
import BackButton from '../common/BackButton';
import GenerateIcon from '../assets/GenerateIcon';
import { Player } from '../common/Players';
import { encoding_for_model } from 'tiktoken';
import { getImageUrl } from '../config/api';

// Tutorial-phase constants
const TUTORIAL_STAGES = {
  GENERATE: 0,
  VOTING: 1, 
  REVEAL: 2,
  RESULT: 3
};

// tutorial guidance card - shows different content per game phase
const tutorialInstructions = [
  {
    stage: TUTORIAL_STAGES.GENERATE,
    title: 'Generate image with short prompt',
    description: 'Given an image, generate a reproduction of that image as close as possible using your prompt, but use as few as possible words!',
    step: '1 of 4'
  },
  {
    stage: TUTORIAL_STAGES.VOTING,
    title: 'Vote on the best image',
    description: 'Now you get to be the judge! Among the images generated by other players, vote on the image most similar to the original image.',
    step: '2 of 4'
  },
  {
    stage: TUTORIAL_STAGES.REVEAL,
    title: 'Watch prompts revealed',
    description: 'Check out the original image\'s prompt and other players\' prompts for their images, and also the voting outcome',
    step: '3 of 4'
  },
  {
    stage: TUTORIAL_STAGES.RESULT,
    title: 'Get scores and reflect',
    description: 'Check out the scores and test out other prompt ideas in quick draw – also check on other player\'s quick draw experiments. Reflect and learn from each other, and do better the next round!',
    step: '4 of 4'
  }
];

// highlight words in the original description that overlap with any user prompt
const highlightOriginalPrompt = (originalDescription, playerPrompts) => {
  if (!originalDescription || !playerPrompts || playerPrompts.length === 0) return originalDescription;
  
  // collect the words from all users' prompts
  const allUserWords = new Set();
  playerPrompts.forEach(prompt => {
    if (prompt) {
      const userWords = prompt.toLowerCase()
        .replace(/[^\w\s]/g, ' ')
        .split(/\s+/)
        .filter(word => word.length > 0);
      userWords.forEach(word => allUserWords.add(word));
    }
  });
  
  // split the original description into words, preserving the original format
  const words = originalDescription.split(/(\s+|[^\w\s]+)/);
  
  return words.map((word, index) => {
    const cleanWord = word.toLowerCase().replace(/[^\w]/g, '');
    
    // check whether it matches any word in the users' prompts
    const isMatch = cleanWord.length > 0 && allUserWords.has(cleanWord);
    
    if (isMatch) {
      return (
        <span key={index} className="bg-[#D7E5FF] text-black px-1 rounded">
          {word}
        </span>
      );
    }
    return word;
  });
};

// function to highlight matching words (copied from RevealPrompt)
const highlightMatchingWords = (prompt, referenceDescription) => {
  if (!prompt || !referenceDescription) return prompt;
  
  // convert the reference description into a lowercase word array for matching
  const referenceWords = referenceDescription.toLowerCase()
    .replace(/[^\w\s]/g, ' ') // replace punctuation with spaces
    .split(/\s+/)
    .filter(word => word.length > 0);
  
  // split the prompt into words, preserving the original format
  const words = prompt.split(/(\s+|[^\w\s]+)/);
  
  return words.map((word, index) => {
    const cleanWord = word.toLowerCase().replace(/[^\w]/g, '');
    
    // check whether it matches any word in the reference description
    const isMatch = cleanWord.length > 0 && referenceWords.includes(cleanWord);
    
    if (isMatch) {
      return (
        <span key={index} className="bg-[#D7E5FF] text-black px-1 rounded">
          {word}
        </span>
      );
    }
    return word;
  });
};


// fixed example image data - using full URLs
const FIXED_EXAMPLE_IMAGES = [
  {
    creator_sid: 'example_player_1',
    creator_name: 'Apple',
    image_url: getImageUrl('/static/tutorial_example_images/giraffe1.png'),
    prompt: 'a cartoon-style giraffe',
    vote_count: 0,
    voter_names: [],
    prompt_tokens: 5 // pre-computed token count
  },
  {
    creator_sid: 'example_player_2', 
    creator_name: 'Pear',
    image_url: getImageUrl('/static/tutorial_example_images/giraffe2.png'),
    prompt: 'A cartoon giraffe with a startled expression farts green gas',
    vote_count: 1,
    voter_names: ['You'],
    prompt_tokens: 12 // pre-computed token count
  }
];

// Fixed reference image used for the tutorial round
const TUTORIAL_REFERENCE_IMAGE = {
  image_path: '/static/reference_images/ref_tutorial.png',
  description: 'Gassy giraffe in cyberpunk maze',
  content: 'Tutorial Reference'
};

// tutorial step card component - simplified, without the toggle buttons
const TutorialInstructionCard = ({ currentStage }) => {
  const currentInstruction = tutorialInstructions.find(inst => inst.stage === currentStage);
  
  if (!currentInstruction) return null;
  
  return (
    <div className="relative overflow-hidden">
      <div className="bg-[#D7E5FF] p-4 border border-black rounded-lg">
        <div className="flex items-start gap-3">
          <div className="flex-1">
            <h3 className="font-medium text-black font-inter mb-2 text-center">
              {currentInstruction.title}
            </h3>
            <p className="text-sm text-gray-700 font-inter leading-relaxed mb-3">
              {currentInstruction.description}
            </p>
            <div className="text-xs text-gray-500 font-inter text-center">
              {currentInstruction.step}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

// Token-counting helper - matches the backend `calculate_prompt_tokens` OpenAI tiktoken count
function calculatePromptTokens(prompt) {
  if (!prompt) return 0;
  const trimmed = String(prompt).trim();
  if (!trimmed) return 0;
  // special handling for the placeholder hint
  if (trimmed === "No prompt submitted") return 0;
  
  // Use GPT-4o encoding for accurate tokenization
  const encoding = encoding_for_model("gpt-4o");
  const tokens = encoding.encode(trimmed);
  return tokens.length;
}

// waiting component - simulates "waiting for other players"
const TutorialWaiting = ({ message, onAutoAdvance }) => {
  useEffect(() => {
    const timer = setTimeout(() => {
      onAutoAdvance();
    }, 2000); // auto-redirect after 2s

    return () => clearTimeout(timer);
  }, [onAutoAdvance]);

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white p-8 rounded-3xl shadow-2xl border-2 border-black max-w-md mx-4 text-center">
        <StageSpinner loading={true} color="#111111" size={50} />
        <h3 className="text-xl font-inter font-semibold text-black mt-4 mb-2">
          {message}
        </h3>
        <p className="text-gray-600 text-sm">
          Auto-advancing in 2 seconds...
        </p>
      </div>
    </div>
  );
};

export default function Tutorial() {
  const navigate = useNavigate();
  
  // basic state
  const [currentStage, setCurrentStage] = useState(TUTORIAL_STAGES.GENERATE);
  const [input, setInput] = useState('');
  const [tokenCount, setTokenCount] = useState(0);

  // API Key state
  const [apiKey, setApiKey] = useState('');
  const [showApiKey, setShowApiKey] = useState(false);
  const [apiKeyError, setApiKeyError] = useState('');
  
  // input optimization - consistent with Generate.jsx
  const inputRef = useRef('');

  // sync the ref on input change, but debounce the token count
  useEffect(() => {
    inputRef.current = input;
  }, [input]);

  // debounced token counting to keep typing smooth - consistent with Generate.jsx
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      setTokenCount(calculatePromptTokens(input));
    }, 300); // 300ms delay

    return () => clearTimeout(timeoutId);
  }, [input]);
  
  // generation state
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);
  const [generatedImages, setGeneratedImages] = useState([]);
  
  // voting state
  const [selectedImage, setSelectedImage] = useState(null);
  const [hasVoted, setHasVoted] = useState(false);
  
  // display state
  const [showWaiting, setShowWaiting] = useState(false);
  const [waitingMessage, setWaitingMessage] = useState('');

  // dynamic voting-result state
  const [voteResults, setVoteResults] = useState({});
  
  // Reveal animation state (copied from RevealPrompt)
  const [visibleCards, setVisibleCards] = useState(new Set());
  const [isAutoProgressing, setIsAutoProgressing] = useState(false);
  const [easingOutCards, setEasingOutCards] = useState(new Set());
  const animationStartedRef = useRef(false);

  // handle instruction navigation
  const handleInstructionNavigate = (direction) => {
    if (direction === 'next' && currentStage < 3) {
      setCurrentStage(currentStage + 1);
    } else if (direction === 'prev' && currentStage > 0) {
      setCurrentStage(currentStage - 1);
    }
  };

  // handle image generation
  const sendMessage = async (e) => {
    e.preventDefault();
    if (!input.trim() || hasGenerated) return;

    // Validate API key before generating
    if (!validateApiKey(apiKey)) {
      return;
    }

    setIsGenerating(true);

    try {
      const response = await axios.post('/api/tutorial-generate-images', {
        prompt: input.trim(),
        api_key: apiKey
      });

      if (response.data.image_url) {
        setGeneratedImages([response.data.image_url]);
        setHasGenerated(true);
      } else {
        throw new Error('No image URL returned');
      }
      
      // after generation, show waiting and auto-advance to the voting phase
      setWaitingMessage('Waiting for other players to generate...');
      setShowWaiting(true);
    } catch (error) {
      console.error('Error generating images:', error);
      setIsGenerating(false);
    }
  };

  // handle voting
  const handleVote = (imageData) => {
    if (hasVoted) return;
    
    setSelectedImage(imageData);
    setHasVoted(true);
    
    // record the voting result
    setVoteResults(prevResults => ({
      ...prevResults,
      [imageData.creator_sid]: (prevResults[imageData.creator_sid] || 0) + 1
    }));
    
    // after voting, show waiting and auto-advance to the Reveal phase
    setWaitingMessage('Waiting for other players to vote...');
    setShowWaiting(true);
  };

  // handle the auto-redirect after waiting
  const handleAutoAdvance = () => {
    setShowWaiting(false);
    setIsGenerating(false);
    
    if (currentStage === TUTORIAL_STAGES.GENERATE && hasGenerated) {
      setCurrentStage(TUTORIAL_STAGES.VOTING);
    } else if (currentStage === TUTORIAL_STAGES.VOTING && hasVoted) {
      // reset the animation state for next time
      setVisibleCards(new Set());
      setIsAutoProgressing(false);
      setEasingOutCards(new Set());
      animationStartedRef.current = false;
      setCurrentStage(TUTORIAL_STAGES.REVEAL);
    } else if (currentStage === TUTORIAL_STAGES.REVEAL) {
      setCurrentStage(TUTORIAL_STAGES.RESULT);
    }
  };
  
  // Reveal-phase auto animation (copied from RevealPrompt)
  useEffect(() => {
    if (currentStage !== TUTORIAL_STAGES.REVEAL) {
      return;
    }
    
    // get the data to display
    const revealData = [];
    if (hasGenerated && generatedImages.length > 0) {
      revealData.push({
        creator_sid: 'user',
        creator_name: 'You',
        image_url: generatedImages[0],
        prompt: input || 'Your prompt',
        voter_names: ['Apple', 'Pear']
      });
    }
    
    FIXED_EXAMPLE_IMAGES.forEach(item => {
      revealData.push({
        ...item,
        voter_names: selectedImage?.creator_sid === item.creator_sid ? ['You'] : []
      });
    });
    
    if (revealData.length === 0 || animationStartedRef.current) {
      return;
    }
    
    console.log('🎭 Starting reveal animation for', revealData.length, 'cards');
    animationStartedRef.current = true;
    setIsAutoProgressing(true);
    
    const timers = [];
    
    // set a fade-in timer for each card (starting after 2s, 800ms apart)
    revealData.forEach((_, index) => {
      const delay = 2000 + (index * 800); // 2s initial delay + increasing delay
      
      const timer = setTimeout(() => {
        setVisibleCards(prev => {
          const newSet = new Set(prev);
          newSet.add(index);
          return newSet;
        });
      }, delay);
      
      timers.push(timer);
    });
    
    // compute the animation end time and set up hold and ease-out logic
    const animationCompleteTime = 2000 + (revealData.length * 800);
    const displayDuration = 3000; // hold for 3s after all cards are shown
    const easeOutInterval = 500; // 500ms between each card's ease-out
    const easeOutAnimationDuration = 700; // each card's ease-out animation lasts 700ms
    
    // set a timer to start easing out after the hold
    const easeOutStartTime = animationCompleteTime + displayDuration;
    
    // set an ease-out timer for each card
    revealData.forEach((_, index) => {
      const easeOutDelay = easeOutStartTime + (index * easeOutInterval);
      
      const easeOutTimer = setTimeout(() => {
        setEasingOutCards(prev => {
          const newSet = new Set(prev);
          newSet.add(index);
          return newSet;
        });
      }, easeOutDelay);
      
      timers.push(easeOutTimer);
    });
    
    // call advanceToNextStage after all cards finish easing out
    const allEaseOutCompleteTime = easeOutStartTime + (revealData.length * easeOutInterval) + easeOutAnimationDuration;
    const finalTimer = setTimeout(() => {
      advanceToNextStage();
    }, allEaseOutCompleteTime);
    
    timers.push(finalTimer);
    
    // return a cleanup function to clear the timers
    return () => {
      timers.forEach(timer => clearTimeout(timer));
    };
  }, [currentStage, hasGenerated, generatedImages, input, selectedImage]);

  // use useMemo to cache final-results data and avoid recomputation
  const finalResults = useMemo(() => {
    let results = [];
    
    // if the user generated an image, add the user's result
    if (hasGenerated && generatedImages.length > 0) {
      // by default the two other AI users vote for the user
      const userVoteCount = 2;
      results.push({
        creator_sid: 'user',
        creator_name: 'You',
        image_url: generatedImages[0],
        prompt: input || 'Your generated image',
        vote_count: userVoteCount,
        voter_names: ['Apple', 'Pear'],
        prompt_tokens: tokenCount // use the cached tokenCount instead of recomputing
      });
    }
    
    // add example images, adjusted by the voting results
    FIXED_EXAMPLE_IMAGES.forEach(item => {
      const userVoteForThisItem = voteResults[item.creator_sid] || 0;
      
      // count only user votes, ignoring the preset vote_count
      const finalVoteCount = userVoteForThisItem;
      
      results.push({
        ...item,
        vote_count: finalVoteCount,
        voter_names: finalVoteCount > 0 ? (selectedImage?.creator_sid === item.creator_sid ? ['You'] : []) : [],
        prompt_tokens: item.prompt_tokens // use the pre-computed token count
      });
    });
    
    // implement the penalty system - consistent with the backend logic
    const promptTokensList = results.map(r => r.prompt_tokens);
    const nonZeroTokens = promptTokensList.filter(tokens => tokens > 0);
    
    // only apply the penalty when there are multiple non-zero players with differing token lengths
    const shouldApplyPenalty = nonZeroTokens.length > 1 && new Set(nonZeroTokens).size > 1;
    const maxTokens = shouldApplyPenalty ? Math.max(...nonZeroTokens) : 0;
    
    // compute the final score for each result
    results = results.map(result => {
      const voteScore = result.vote_count;
      const penalty = (shouldApplyPenalty && result.prompt_tokens > 0 && result.prompt_tokens === maxTokens) ? 1 : 0;
      const finalScore = Math.max(0, voteScore - penalty);
      
      return {
        ...result,
        score_info: {
          total_score: finalScore,
          vote_score: voteScore,
          penalty: penalty,
          prompt_tokens: result.prompt_tokens
        }
      };
    });
    
    // sort by score
    results.sort((a, b) => b.score_info.total_score - a.score_info.total_score);
    
    return results;
  }, [hasGenerated, generatedImages, tokenCount, voteResults, selectedImage]);

  // API key validation function
  const validateApiKey = (key) => {
    if (!key || key.trim() === '') {
      setApiKeyError('OpenAI API key is required for image generation');
      return false;
    }
    if (!key.startsWith('sk-')) {
      setApiKeyError('API key must start with "sk-"');
      return false;
    }
    if (key.length < 20) {
      setApiKeyError('API key appears to be too short');
      return false;
    }
    setApiKeyError('');
    return true;
  };

  // Check if API key is valid
  const isApiKeyValid = apiKey && apiKey.trim() !== '' && apiKey.startsWith('sk-') && apiKey.length >= 20;

  // manually advance to the next phase (for the Reveal and Result phases)
  const advanceToNextStage = () => {
    if (currentStage === TUTORIAL_STAGES.REVEAL) {
      setCurrentStage(TUTORIAL_STAGES.RESULT);
    } else if (currentStage === TUTORIAL_STAGES.RESULT) {
      // tutorial finished, go back home
      navigate('/');
    }
  };

  // use useMemo to cache player data and avoid recomputation
  const tutorialPlayers = useMemo(() => {
    const players = [];
    
    // build the player ranking
    finalResults.forEach((result, index) => {
      players.push({
        rank: index + 1,
        name: result.creator_name,
        points: result.score_info.total_score
      });
    });
    
    // if no image was generated, add a default player
    if (!hasGenerated) {
      const defaultPlayers = [
        { rank: 1, name: 'You', points: 0 },
        { rank: 1, name: 'Apple', points: 0 },
        { rank: 1, name: 'Pear', points: 0 }
      ];
      return defaultPlayers;
    }
    
    return players;
  }, [finalResults, hasGenerated]);

  const TutorialPlayerContainer = () => (
    <div className="bg-white rounded-[1rem] border-black border-[0.063rem]">
      <div className="p-[0.625rem] bg-black rounded-t-[0.75rem] text-white text-center font-medium text-[1.25rem] font-gooper">
        <div>Tutorial Round</div>
        <div className="font-inter text-[0.8rem] font-normal text-[#D9D9D9] mt-1">
          Points earned during the tutorial won't count toward your gameplay score.
        </div>
      </div>
      {tutorialPlayers.map((player) => (
        <Player
          key={player.name}
          rank={player.rank}
          name={player.name}
          points={player.points}
        />
      ))}
    </div>
  );

  // API Key Input Component - only shown during Generate phase
  const TutorialApiKeyInput = () => {
    if (currentStage !== TUTORIAL_STAGES.GENERATE) return null;

    return (
      <div className="bg-white rounded-[1rem] border-black border-[0.063rem] mb-4">
        <div className="p-[0.625rem] bg-[#D7E5FF] rounded-t-[0.75rem] text-black text-center font-medium text-[1.25rem] font-gooper">
          <div>🔑 API Key Required</div>
        </div>
        <div className="p-4">
          <label
            htmlFor="tutorial-api-key"
            className="block text-sm font-medium text-gray-700 mb-2"
          >
            OpenAI API Key (Required to generate)
          </label>
          <div className="relative">
            <input
              type={showApiKey ? "text" : "password"}
              value={apiKey}
              onChange={(e) => {
                const value = e.target.value;
                setApiKey(value);

                // Update error message based on current value
                if (!value || value.trim() === '') {
                  setApiKeyError('OpenAI API key is required for image generation');
                } else if (!value.startsWith('sk-')) {
                  setApiKeyError('API key must start with "sk-"');
                } else if (value.length < 20) {
                  setApiKeyError('API key appears to be too short');
                } else {
                  setApiKeyError('');
                }
              }}
              id="tutorial-api-key"
              name="tutorial-api-key"
              className={`w-full px-3 py-2 text-sm border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                apiKeyError ? 'border-red-500' : 'border-gray-300'
              }`}
              placeholder="sk-..."
            />
            <button
              type="button"
              onClick={() => setShowApiKey(!showApiKey)}
              className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 hover:text-gray-700 text-sm"
            >
              {showApiKey ? "🙈" : "👁️"}
            </button>
          </div>
          <p className="text-xs text-gray-500 mt-1">
            Your API key is only used for this tutorial session.
          </p>
          {apiKeyError && (
            <p className="text-xs text-red-600 mt-1">{apiKeyError}</p>
          )}
        </div>
      </div>
    );
  };

  // render content per phase
  const renderStageContent = () => {
    switch (currentStage) {
      case TUTORIAL_STAGES.GENERATE:
        return (
          <div className="bg-[#D7E5FF] p-5 rounded-t-[1.25rem] border-b-black border-b-[0.063rem]">
            <div className="flex justify-center items-center gap-4 mb-2">
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('prev')}
                disabled={currentStage === 0}
              >
                <i className="fa-solid fa-chevron-left text-xl"></i>
              </button>
              
              <div className="flex items-center gap-2">
                <GenerateIcon />
                <h2 className="font-medium text-[1.5rem] font-gooper">Generate an image</h2>
              </div>
              
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('next')}
                disabled={currentStage === 3}
              >
                <i className="fa-solid fa-chevron-right text-xl"></i>
              </button>
            </div>
            <p className="text-center text-[#4E4E4E] font-inter">
              Generate an image that best recreates the given image with as few as possible words in prompt.
            </p>
          </div>
        );
      
      case TUTORIAL_STAGES.VOTING:
        return (
          <div className="bg-[#D7E5FF] p-5 rounded-t-[1.25rem] border-b-black border-b-[0.063rem]">
            <div className="flex justify-center items-center gap-4 mb-2">
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('prev')}
                disabled={currentStage === 0}
              >
                <i className="fa-solid fa-chevron-left text-xl"></i>
              </button>
              
              <div className="flex items-center gap-2">
                <i className="fa-solid fa-vote-yea text-2xl"></i>
                <h2 className="font-medium text-[1.5rem] font-gooper">Vote on the best image</h2>
              </div>
              
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('next')}
                disabled={currentStage === 3}
              >
                <i className="fa-solid fa-chevron-right text-xl"></i>
              </button>
            </div>
            <p className="text-center text-[#4E4E4E] font-inter">
              Select the image that best matches the original reference image.
            </p>
          </div>
        );
      
      case TUTORIAL_STAGES.REVEAL:
        return (
          <div className="bg-[#D7E5FF] p-5 rounded-t-[1.25rem] border-b-black border-b-[0.063rem]">
            <div className="flex justify-center items-center gap-4 mb-2">
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('prev')}
                disabled={currentStage === 0}
              >
                <i className="fa-solid fa-chevron-left text-xl"></i>
              </button>
              
              <div className="flex items-center gap-2">
                <i className="fa-solid fa-eye text-2xl"></i>
                <h2 className="font-medium text-[1.5rem] font-gooper">Prompts Revealed</h2>
              </div>
              
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('next')}
                disabled={currentStage === 3}
              >
                <i className="fa-solid fa-chevron-right text-xl"></i>
              </button>
            </div>
            <p className="text-center text-[#4E4E4E] font-inter">
            Check out the original image’s prompt and other players’ prompts for their images, and also the voting outcome.
            </p>
          </div>
        );
      
      case TUTORIAL_STAGES.RESULT:
        return (
          <div className="bg-[#D7E5FF] p-5 rounded-t-[1.25rem] border-b-black border-b-[0.063rem]">
            <div className="flex justify-center items-center gap-4 mb-2">
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('prev')}
                disabled={currentStage === 0}
              >
                <i className="fa-solid fa-chevron-left text-xl"></i>
              </button>
              
              <div className="flex items-center gap-2">
                <i className="fa-solid fa-trophy text-2xl"></i>
                <h2 className="font-medium text-[1.5rem] font-gooper">Round Results</h2>
              </div>
              
              <button 
                className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                onClick={() => handleInstructionNavigate('next')}
                disabled={currentStage === 3}
              >
                <i className="fa-solid fa-chevron-right text-xl"></i>
              </button>
            </div>
            <p className="text-center text-[#4E4E4E] font-inter">
              Review scores, prompts and learn from other players' strategies.
            </p>
          </div>
        );
      
      default:
        return null;
    }
  };

  const renderMainContent = () => {
    switch (currentStage) {
      case TUTORIAL_STAGES.GENERATE:
        return (
          <div className="flex h-[45rem] w-full px-8 gap-6">
            {/* left-side reference-image area */}
            <div className="w-1/4 flex flex-col">
              <h3 className="text-lg font-inter font-medium mb-3 text-center">Reference Image</h3>
              <div className="flex-1 border border-gray-300 rounded-2xl p-4 bg-gray-50 flex flex-col items-center justify-center">
                <div className="flex flex-col items-center">
                  <img
                    src={getImageUrl(TUTORIAL_REFERENCE_IMAGE.image_path)}
                    alt={TUTORIAL_REFERENCE_IMAGE.description}
                    className="max-w-full max-h-[20rem] rounded-xl object-contain mb-3"
                    onError={(e) => {
                      console.error('Failed to load image:', e.target.src);
                      e.target.style.display = 'none';
                    }}
                  />
                  <div className="text-center">
                    <p className="font-medium text-gray-800">Original Image</p>
                    <p className="text-sm text-gray-600 mt-1">Reference for your creation</p>
                  </div>
                </div>
              </div>
            </div>
            
            {/* right-side generation area */}
            <div className="w-3/4 flex flex-col">
              <div className="flex-1 flex flex-col p-4">
                {isGenerating ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-4">
                    <div className="w-[30rem] h-[30rem] bg-[#DDDDDD] rounded-[1.3rem] flex flex-col items-center justify-center">
                      <div className="relative mb-6">
                        <FireworkSpinner size={100} thickness={15} color="black" />
                        <i className="fa-solid fa-image absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-5xl text-gray-600" />
                      </div>
                      <div className="flex flex-col items-center text-center">
                        <p className="text-lg text-gray-600">Generating your image...</p>
                        <p className="text-sm text-gray-500 mt-1">Please wait, this may take a few moments</p>
                      </div>
                    </div>
                  </div>
                ) : hasGenerated ? (
                  <div className="flex-1 flex flex-col items-center justify-center p-4">
                    <div className="w-[30rem] h-[30rem] rounded-[1.3rem] relative overflow-hidden shadow-lg">
                      <img
                        src={generatedImages[0]}
                        className="w-[30rem] h-[30rem] rounded-[1.3rem] object-cover"
                        alt="Generated image"
                      />
                      <div className="absolute bottom-4 left-0 right-0 flex flex-col items-center bg-black bg-opacity-60 text-white py-2 mx-4 rounded-lg">
                        <div className="flex items-center mb-1">
                          <i className="fa-solid fa-check text-green-400 mr-2"></i>
                          <p className="text-sm">Image generated successfully!</p>
                        </div>
                        <p className="text-xs text-gray-200">
                          Great job! Now let's move to voting.
                        </p>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex-1 flex flex-col items-center justify-center p-4">
                    <div className="w-[30rem] h-[30rem] bg-[#DDDDDD] rounded-[1.3rem] flex flex-col items-center justify-center">
                      <div className="flex flex-col items-center text-center">
                        <i className="fa-solid fa-image text-6xl text-gray-500 mb-4"></i>
                        <p className="text-lg text-gray-600 mb-2">No image generated yet</p>
                        <p className="text-sm text-gray-500">
                        Enter an image prompt below to generate an image
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* input area */}
              <div className="border border-[#E8E8E8] bg-[#FAFAFA] pl-[1rem] border-[0.0625rem] rounded-[2rem] h-fit">
                <form onSubmit={sendMessage} className="flex p-2">
                  <input
                    type="text"
                    className="bg-transparent w-full focus:outline-none"
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    placeholder={hasGenerated ? "Image already generated" : "Enter your image prompt"}
                    maxLength={4000}
                    disabled={hasGenerated}
                  />
                  <div className="text-sm text-gray-500 text-right content-center pr-2 whitespace-nowrap">
                    {tokenCount} tokens
                  </div>

                  <button
                    type="submit"
                    disabled={isGenerating || hasGenerated || !input.trim() || !isApiKeyValid}
                    className={`rounded-[4.9375rem] w-[2.5rem] h-[2.5rem] text-white transition-colors ${
                      isGenerating || hasGenerated || !input.trim() || !isApiKeyValid
                        ? 'bg-gray-400 cursor-not-allowed'
                        : 'bg-black hover:bg-gray-800'
                    }`}
                  >
                    {isGenerating ? (
                      <MetroSpinner loading={true} color="#ffffff" size={20} />
                    ) : (
                      <i className="fa-solid fa-arrow-up"></i>
                    )}
                  </button>
                </form>
              </div>
            </div>
          </div>
        );

      case TUTORIAL_STAGES.VOTING:
        return (
          <div className="flex h-[45rem] w-full px-8 gap-6">
            {/* left-side reference-image area */}
            <div className="w-1/4 flex flex-col">
              <h3 className="text-lg font-inter font-medium mb-3 text-center">Reference Image</h3>
              <div className="flex-1 border border-gray-300 rounded-2xl p-4 bg-gray-50 flex flex-col items-center justify-center">
                <div className="flex flex-col items-center">
                  <img
                    src={getImageUrl(TUTORIAL_REFERENCE_IMAGE.image_path)}
                    alt={TUTORIAL_REFERENCE_IMAGE.description}
                    className="max-w-full max-h-[20rem] rounded-xl object-contain mb-3"
                  />
                  <div className="text-center">
                    <p className="font-medium text-gray-800">Original Image</p>
                    <p className="text-sm text-gray-600 mt-1">Reference for voting</p>
                  </div>
                </div>
              </div>
            </div>
            
            {/* right-side voting area */}
            <div className="w-3/4 flex flex-col">
              <div className="flex-1 flex flex-col items-center justify-center">
                <div className="mb-8">
                  <div className="flex font-inter text-center bg-black text-white rounded-[0.5rem] border-black border-[0.063rem] gap-x-2 pt-2 pb-2 pl-4 pr-4 text-[1.25rem] font-semibold items-center whitespace-nowrap">
                    <i className="fa-regular fa-clock"></i>
                    <p>No Time Limit (Tutorial)</p>
                  </div>
                </div>
                
                <div className="flex gap-8 justify-center">
                  {/* users cannot vote for themselves, so the user's own image is not shown */}
                  {FIXED_EXAMPLE_IMAGES.map((imageData, index) => (
                    <div 
                      key={index}
                      className={`w-80 h-96 border-2 rounded-3xl p-4 transition-all cursor-pointer flex flex-col shadow-lg ${
                        selectedImage?.creator_sid === imageData.creator_sid
                          ? 'border-green-500 bg-green-50 shadow-green-200' 
                          : hasVoted
                          ? 'border-gray-300 bg-gray-100 cursor-not-allowed opacity-60'
                          : 'border-gray-300 hover:border-blue-400 hover:bg-blue-50 hover:shadow-blue-200'
                      }`}
                      onClick={() => !hasVoted && handleVote(imageData)}
                    >
                      <div className="flex flex-col items-center w-full h-full">
                        <img
                          src={imageData.image_url}
                          alt={`Image ${index + 1}`}
                          className="w-full flex-1 rounded-2xl object-contain"
                          onError={(e) => {
                            console.error('Failed to load image:', e.target.src);
                            e.target.style.display = 'none';
                          }}
                        />
                        <div className="mt-3 text-center">
                          <p className="font-semibold text-lg text-gray-800">
                            Image {index + 1}
                          </p>
                          {selectedImage?.creator_sid === imageData.creator_sid && (
                            <div className="mt-2 flex items-center justify-center text-green-600">
                              <i className="fa-solid fa-check mr-2"></i>
                              <span className="font-medium">Selected!</span>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
                
                {hasVoted && (
                  <div className="mt-8 p-4 bg-green-100 border border-green-300 rounded-2xl text-center max-w-md">
                    <div className="text-green-600 font-medium">
                      ✅ Vote submitted! Moving to reveal phase...
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        );

      case TUTORIAL_STAGES.REVEAL:
        // prepare the data to display
        const revealData = [];
        if (hasGenerated && generatedImages.length > 0) {
          revealData.push({
            creator_sid: 'user',
            creator_name: 'You',
            image_url: generatedImages[0],
            prompt: input || 'Your prompt',
            voter_names: ['Apple', 'Pear']
          });
        }
        
        FIXED_EXAMPLE_IMAGES.forEach(item => {
          revealData.push({
            ...item,
            voter_names: selectedImage?.creator_sid === item.creator_sid ? ['You'] : []
          });
        });
        
        return (
          <div className="flex h-[45rem] w-full px-8 gap-6">
            {/* left-side reference-image area */}
            <div className="w-1/4 flex flex-col">
              <h3 className="text-lg font-inter font-medium mb-3 text-center">Reference Image</h3>
              <div className="flex-1 border border-gray-300 rounded-2xl p-4 bg-gray-50 flex flex-col items-center justify-center">
                <div className="flex flex-col items-center">
                  <img
                    src={getImageUrl(TUTORIAL_REFERENCE_IMAGE.image_path)}
                    alt={TUTORIAL_REFERENCE_IMAGE.description}
                    className="max-w-full max-h-[20rem] rounded-xl object-contain mb-3"
                  />
                  <div className="text-center">
                    <p className="font-medium text-gray-800">Original Image</p>
                    <p className="text-sm text-gray-600 mt-1">{TUTORIAL_REFERENCE_IMAGE.description}</p>
                  </div>
                </div>
              </div>
            </div>
            
            {/* right-side results display area */}
            <div className="w-2/3 flex flex-col">
              <h3 className="text-lg font-inter font-medium mb-3 text-center">
                Prompts Revealed!
              </h3>
              
              <div className="flex-1 overflow-auto p-4">
                <div className="grid grid-cols-2 gap-6">
                  {revealData.map((item, index) => {
                    const isVisible = visibleCards.has(index);
                    const isEasingOut = easingOutCards.has(index);
                    
                    return (
                      <div 
                        key={item.creator_sid}
                        className={`border-2 border-gray-300 rounded-2xl p-4 bg-white shadow-sm transition-all duration-700 ease-out transform ${
                          isEasingOut
                            ? 'opacity-0 scale-95 translate-y-8 -translate-x-4'
                            : isVisible
                            ? 'opacity-100 scale-100 translate-y-0' 
                            : 'opacity-0 scale-95 translate-y-4'
                        }`}
                        style={{
                          animationDelay: `${index * 0.2}s`
                        }}
                      >
                        {/* Image */}
                        <div className={`mb-4 transition-all duration-500 ${
                          isEasingOut
                            ? 'opacity-0 transform translate-y-4 scale-95'
                            : isVisible
                            ? 'opacity-100 transform translate-y-0' 
                            : 'opacity-0 transform translate-y-2'
                        }`}
                        style={{ transitionDelay: `${index * 0.2 + 0.1}s` }}>
                          <img
                            src={item.image_url}
                            alt={`Creation by ${item.creator_name}`}
                            className="w-full h-full rounded-xl object-cover shadow-lg"
                            onError={(e) => {
                              console.error('Failed to load image:', e.target.src);
                              e.target.style.display = 'none';
                            }}
                          />
                        </div>
                        
                        {/* Prompt with highlighting */}
                        <div className={`mb-3 transition-all duration-500 ${
                          isEasingOut
                            ? 'opacity-0 transform translate-y-4 scale-95'
                            : isVisible
                            ? 'opacity-100 transform translate-y-0' 
                            : 'opacity-0 transform translate-y-2'
                        }`}
                        style={{ transitionDelay: `${index * 0.2 + 0.2}s` }}>
                          <div className="bg-gradient-to-r from-gray-50 to-gray-100 p-3 rounded-lg border border-gray-200">
                            <p className="text-sm font-medium text-gray-700 mb-1">Prompt:</p>
                            <p className="text-sm text-gray-600 italic">
                              "{highlightMatchingWords(item.prompt, TUTORIAL_REFERENCE_IMAGE.description)}"
                            </p>
                          </div>
                        </div>
                        
                        {/* Voter */}
                        <div className={`transition-all duration-500 ${
                          isEasingOut
                            ? 'opacity-0 transform translate-y-4 scale-95'
                            : isVisible
                            ? 'opacity-100 transform translate-y-0' 
                            : 'opacity-0 transform translate-y-2'
                        }`}
                        style={{ transitionDelay: `${index * 0.2 + 0.3}s` }}>
                          {item.voter_names.length > 0 ? (
                            <div className="flex flex-wrap gap-2">
                              {item.voter_names.map((voterName, voterIndex) => (
                                <span 
                                  key={voterIndex}
                                  className="inline-block bg-gradient-to-r from-blue-100 to-blue-200 text-blue-800 px-3 py-1 rounded-full text-sm shadow-sm"
                                >
                                  ❤️ {voterName}
                                </span>
                              ))}
                            </div>
                          ) : (
                            <div className="text-center py-2">
                              <span className="text-gray-400 text-sm">No votes received</span>
                            </div>
                          )}
                        </div>
                      </div>
                    );
                  })}
                </div>
                
                {!isAutoProgressing && (
                  <div className="mt-6 text-center">
                    <button
                      className="bg-black text-white px-6 py-2 rounded-xl font-semibold hover:bg-gray-800 transition-colors"
                      onClick={advanceToNextStage}
                    >
                      Continue to Results
                    </button>
                  </div>
                )}
              </div>
            </div>
          </div>
        );

      case TUTORIAL_STAGES.RESULT:
        return (
          <div className="flex h-[45rem] w-full px-8">
            <div className="w-full flex flex-col bg-white rounded-2xl border-2 border-black shadow-lg">
              {/* title area */}
              <div className="rounded-t-[1.25rem] overflow-hidden">
                <div className="bg-[#D7E5FF] p-5">
                  <div className="flex justify-center items-center gap-4 mb-3">
                    <button 
                      className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                      onClick={() => handleInstructionNavigate('prev')}
                      disabled={currentStage === 0}
                    >
                      <i className="fa-solid fa-chevron-left text-xl"></i>
                    </button>
                    
                    <div className="flex items-center gap-2">
                      <i className="fa-solid fa-trophy text-2xl"></i>
                      <h2 className="text-3xl font-gooper font-bold">
                        Tutorial Results
                      </h2>
                    </div>
                    
                    <button 
                      className="text-gray-600 hover:text-gray-800 disabled:text-gray-400 disabled:cursor-not-allowed p-2"
                      onClick={() => handleInstructionNavigate('next')}
                      disabled={currentStage === 3}
                    >
                      <i className="fa-solid fa-chevron-right text-xl"></i>
                    </button>
                  </div>
                </div>
                <div className="bg-gray-100 text-center">
                  <p className="text-lg text-gray-800 px-0 py-4">
                    Great job completing the tutorial!
                  </p>
                </div>
              </div>

              {/* reference-image area */}
              <div className="px-6 py-2 border-b border-gray-200">
                <div className="flex items-center gap-8 py-2 bg-gray-50 rounded-lg px-4 py-4">
                  <div className="flex min-w-0 w-72">
                    <span className="text-black font-bold text-sm whitespace-nowrap">Original Image</span>
                  </div>
                  
                  <div className="flex items-center flex-1 gap-6">
                    <div className="w-24 h-24">
                      <img
                        src={getImageUrl(TUTORIAL_REFERENCE_IMAGE.image_path)}
                        alt={TUTORIAL_REFERENCE_IMAGE.description}
                        className="w-24 h-24 rounded-lg object-cover border border-gray-200"
                      />
                    </div>
                    
                    <div className="flex-1 min-w-0">
                      <p className="text-xs text-gray-500 mb-1">Prompt</p>
                      <p className="text-sm font-medium">
                        {highlightOriginalPrompt(
                          TUTORIAL_REFERENCE_IMAGE.description,
                          finalResults.map(item => item.prompt)
                        )}
                      </p>
                    </div>
                  </div>
                  
                  <div className="text-center min-w-[120px]">
                    <div className="text-xl font-bold">
                      {calculatePromptTokens(TUTORIAL_REFERENCE_IMAGE.description)}
                    </div>
                    <div className="text-xs text-gray-500">
                      Tokens
                    </div>
                  </div>
                  
                  <div className="text-center min-w-[60px]"></div>
                </div>
              </div>
              
              {/* results list */}
              <div className="flex-1 overflow-auto px-6">
                <div className="space-y-2 mt-4">
                  {finalResults.map((item, index) => (
                    <React.Fragment key={item.creator_sid}>
                      <div className="flex items-center gap-8 py-2">
                        <div className="flex min-w-0 w-72 relative">
                          <div className="bg-white border border-gray-300 px-3 py-2 rounded-full">
                            <span className="text-black font-bold text-sm whitespace-nowrap">{item.creator_name}</span>
                          </div>
                          <div className="bg-green-500 text-white px-3 py-2 rounded-full text-sm font-bold whitespace-nowrap absolute left-52">
                            + {item.score_info.total_score} points
                          </div>
                        </div>
                        
                        <div className="flex items-center flex-1 gap-6">
                          <div className="w-24 h-24">
                            <img
                              src={item.image_url}
                              alt={`Creation by ${item.creator_name}`}
                              className="w-24 h-24 rounded-lg object-cover border border-gray-200"
                            />
                          </div>
                          
                          <div className="flex-1 min-w-0">
                            <p className="text-xs text-gray-500 mb-1">Prompt</p>
                            <p className="text-sm font-medium">{highlightMatchingWords(item.prompt, TUTORIAL_REFERENCE_IMAGE.description)}</p>
                          </div>
                        </div>
                        
                        <div className="text-center min-w-[120px]">
                          <div className="text-xl font-bold">
                            {item.score_info.prompt_tokens}
                          </div>
                          <div className="text-xs text-gray-500">Tokens</div>
                          {item.score_info.penalty > 0 && (
                            <div className="text-red-500 text-xs mt-1">-1 for longest prompt</div>
                          )}
                        </div>
                        
                        <div className="text-center min-w-[60px]">
                          <div className="text-xl font-bold">{item.vote_count}</div>
                          <div className="text-xs text-gray-500">Votes</div>
                          {item.score_info.total_score > 0 && (
                            <div className="text-green-500 text-xs mt-1">+{item.score_info.total_score} point{item.score_info.total_score > 1 ? 's' : ''}</div>
                          )}
                        </div>
                      </div>
                      {index < finalResults.length - 1 && (
                        <div className="h-px bg-gray-200/60" />
                      )}
                    </React.Fragment>
                  ))}
                </div>
              </div>
              
              {/* bottom button area */}
              <div className="flex items-center gap-4 p-4 border-t-2 border-gray-200">
                <div className="flex-1 flex items-center gap-2 text-gray-800 bg-gray-100 px-4 py-2 rounded-lg">
                  <span className="text-base">Discuss time! Share your thoughts with other players and feel free to try two more prompts!</span>
                </div>
                <button
                  className="bg-black text-white px-6 py-2 rounded-xl font-semibold hover:bg-gray-800 transition-colors"
                  onClick={advanceToNextStage}
                >
                  Finish Tutorial
                </button>
              </div>
            </div>
          </div>
        );

      default:
        return null;
    }
  };

  // Tutorial Quick Draw Component with real functionality
  const TutorialQuickDraw = () => {
    const [quickDrawPrompt, setQuickDrawPrompt] = useState('');
    const [quickDrawImages, setQuickDrawImages] = useState([]);
    const [attemptsLeft, setAttemptsLeft] = useState(2);
    const [isGeneratingQuickDraw, setIsGeneratingQuickDraw] = useState(false);
    const [selectedPlayerId, setSelectedPlayerId] = useState('You');
    const [displayedResults, setDisplayedResults] = useState([]);
    const [allPlayersResults, setAllPlayersResults] = useState([]);
    
    // Mock other players' Quick Draw results
    const mockOtherPlayersResults = [
      {
        player_name: 'Apple',
        quick_draws: [
          { prompt: 'cute giraffe cartoon', image_url: getImageUrl('/static/tutorial_example_images/cute_giraffe.png'), timestamp: Date.now() - 60000 },
        ]
      },
      {
        player_name: 'Pear', 
        quick_draws: [
          { prompt: 'funny giraffe with big eyes', image_url: getImageUrl('/static/tutorial_example_images/funny_giraffe.png'), timestamp: Date.now() - 30000 },
        ]
      }
    ];
    
    // Initialize mock data
    useEffect(() => {
      setAllPlayersResults(mockOtherPlayersResults);
      // Default to showing current player results
      setDisplayedResults(quickDrawImages);
    }, []);
    
    // Update displayed results when switching players
    const switchToPlayer = (playerName) => {
      setSelectedPlayerId(playerName);
      if (playerName === 'You') {
        setDisplayedResults(quickDrawImages);
      } else {
        const playerData = allPlayersResults.find(p => p.player_name === playerName);
        if (playerData) {
          setDisplayedResults(playerData.quick_draws.map(qd => ({
            prompt: qd.prompt,
            imageUrl: qd.image_url,
            timestamp: qd.timestamp
          })));
        } else {
          setDisplayedResults([]);
        }
      }
    };
    
    // Update displayed results when current player's images change
    useEffect(() => {
      if (selectedPlayerId === 'You') {
        setDisplayedResults(quickDrawImages);
      }
    }, [quickDrawImages, selectedPlayerId]);
    
    // Real Quick Draw generation using API
    const handleQuickDraw = async () => {
      if (!quickDrawPrompt.trim() || attemptsLeft <= 0 || isGeneratingQuickDraw) return;

      // Use the API key from the parent scope if available, otherwise fallback to mock
      if (!isApiKeyValid) {
        console.warn('No valid API key available, using mock generation');
      }

      setIsGeneratingQuickDraw(true);
      try {
        const response = await axios.post('/api/tutorial-quick-draw', {
          prompt: quickDrawPrompt.trim(),
          api_key: apiKey
        });

        if (response.data.image_url) {
          const newImage = {
            prompt: quickDrawPrompt.trim(),
            imageUrl: response.data.image_url,
            timestamp: Date.now()
          };
          setQuickDrawImages(prev => [...prev, newImage]);
          setAttemptsLeft(prev => prev - 1);
          setQuickDrawPrompt('');
        } else if (response.data.error) {
          throw new Error(response.data.error);
        }
      } catch (error) {
        console.error('Error generating quick draw:', error);
        // Show error message to user instead of fallback
        alert(`Quick Draw generation failed: ${error.response?.data?.error || error.message}`);
      } finally {
        setIsGeneratingQuickDraw(false);
      }
    };
    
    return (
      <div className="rounded-[1rem] border-black border-[0.063rem] h-full flex flex-col overflow-hidden">
        <div className="bg-[#D7E5FF] p-4">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-xl">⚡</span>
            <h3 className="font-gooper font-bold text-lg">Quick Draws!</h3>
          </div>
          <p className="text-sm text-gray-700">Any prompt you wanna try really quick?</p>
        </div>
        
        <div className="bg-white p-4 flex flex-col flex-1">
          {/* Player switching buttons */}
          <div className="flex justify-center gap-2 mb-3">
            <button
              onClick={() => switchToPlayer('You')}
              className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                selectedPlayerId === 'You'
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
              }`}
            >
              You
            </button>
            
            {allPlayersResults.map((player) => (
              <button
                key={player.player_name}
                onClick={() => switchToPlayer(player.player_name)}
                className={`px-3 py-1 rounded-lg text-xs font-medium transition-colors ${
                  selectedPlayerId === player.player_name
                    ? 'bg-blue-500 text-white'
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                {player.player_name}
              </button>
            ))}
          </div>
          
          {/* Only show attempts left when viewing own results */}
          {selectedPlayerId === 'You' && (
            <div className="bg-black text-white rounded-lg px-3 py-2 text-center font-medium mb-4">
              {attemptsLeft} attempts left
            </div>
          )}
          
          <div className="flex-1 mb-3 overflow-y-auto min-h-0 max-h-80">
            <div className="space-y-3">
              {displayedResults.map((item, index) => (
                <div key={item.timestamp} className="border border-gray-300 rounded-lg p-3 bg-white">
                  <img
                    src={getImageUrl(item.imageUrl)}
                    alt={`Quick draw ${index + 1}`}
                    className="w-full h-auto rounded-lg mb-2"
                    onError={(e) => {
                      console.error('Failed to load image:', e.target.src);
                      e.target.style.display = 'none';
                    }}
                  />
                  <p className="text-xs text-gray-600 font-medium text-center">"{item.prompt}"</p>
                </div>
              ))}
              
              {displayedResults.length === 0 && (
                <div className="bg-gray-200 rounded-lg border-2 border-dashed border-gray-300 flex flex-col items-center justify-center p-8">
                  <div className="text-4xl mb-2 text-gray-400">🖼️</div>
                  <p className="text-sm text-gray-500 text-center">No image generated yet</p>
                  {selectedPlayerId === 'You' && (
                    <p className="text-xs text-gray-400 text-center">You have two chances to test your prompt below.</p>
                  )}
                </div>
              )}
            </div>
          </div>
          
          {/* Input area only shown when viewing own results */}
          {selectedPlayerId === 'You' && (
            <div className="flex gap-2">
              <input
                type="text"
                value={quickDrawPrompt}
                onChange={(e) => setQuickDrawPrompt(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleQuickDraw()}
                placeholder="Try your prompts here!"
                className="flex-1 p-3 border border-gray-300 rounded-lg focus:outline-none focus:border-blue-500"
                disabled={attemptsLeft <= 0 || isGeneratingQuickDraw}
              />
              <button
                onClick={handleQuickDraw}
                disabled={!quickDrawPrompt.trim() || attemptsLeft <= 0 || isGeneratingQuickDraw}
                className="w-12 h-12 bg-black text-white rounded-lg hover:bg-gray-800 disabled:bg-gray-300 disabled:cursor-not-allowed flex items-center justify-center"
              >
                {isGeneratingQuickDraw ? (
                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                ) : (
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
                  </svg>
                )}
              </button>
            </div>
          )}
        </div>
      </div>
    );
  };

  return (
    <>
      {/* waiting overlay */}
      {showWaiting && (
        <TutorialWaiting 
          message={waitingMessage}
          onAutoAdvance={handleAutoAdvance}
        />
      )}
      
      <div className="grid grid-cols-4">
        <TopBar />
        <div className="col-start-4">
          {/* show the timer only during the generation phase */}
          {currentStage === TUTORIAL_STAGES.GENERATE && (
            <div className="flex font-inter mt-8 mr-8 text-center place-self-end bg-black text-white rounded-[0.5rem] border-black border-[0.063rem] gap-x-2 pt-2 pb-2 pl-3 pr-3 text-[1.25rem] font-semibold items-center">
              <i className="fa-regular fa-clock"></i>
              <p>01:10 for actual game</p>
            </div>
          )}
        </div>
        <div className="col-start-1 mt-7 ml-8 grid grid-cols-1 content-between">
          <TutorialPlayerContainer />
          {/* Quick Draw only shows in Result stage */}
          {currentStage === TUTORIAL_STAGES.RESULT && (
            <div className="mb-4">
              <TutorialQuickDraw />
            </div>
          )}
          {/* API Key Input only shows in Generate stage */}
          <TutorialApiKeyInput />
          <div className="mb-4">
            <TutorialInstructionCard
              currentStage={currentStage}
            />
          </div>
        </div>
        <div className="col-start-2 col-span-full m-7 h-full">
          {currentStage === TUTORIAL_STAGES.RESULT ? (
            // the Result phase does not need the Container wrapper
            renderMainContent()
          ) : (
            <Container>
              {renderStageContent()}
              <BackButton />
              <div className="mt-7 pb-8">
                {renderMainContent()}
              </div>
            </Container>
          )}
        </div>
      </div>
    </>
  );
}